version: '3.7'

volumes:
  caddy-volume:

services:
  caddy:
    image: abiosoft/caddy:0.11.0-no-stats
    container_name: caddy
    ports:
      - '80'
      - '443'
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - ./index.html:/srv/index.html
      # - caddy-volume:/root/.caddy

  v2ray:
    image: v2ray/official:latest
    container_name: v2ray
    ports:
      - '9527'
    volumes:
      - ./config.json:/etc/v2ray/config.json
